services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  api:
    build:
      context: ./api
    volumes:
      - ./api:/usr/src/app/:Z
    ports:
      - 8000:8000
    expose:
      - 8000
    command: python startserver.py
    depends_on:
      - postgres
    environment:
      - POSGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  inference:
    # build:
    #   context: ./inference
    image: vertolis/something:latest
    command: python3 /usr/src/app/script.py
    volumes:
      - ./inference:/usr/src/app:Z
    depends_on:
      - ffmpeg
      - mediamtx
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  webapp:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/home/app/:Z
    command: npm run dev
    ports:
      - 3000:3000
    depends_on:
      - api
      - mediamtx
  mediamtx:
    image: bluenviron/mediamtx:latest-ffmpeg
    environment:
      - MTX_PROTOCOLS=tcp
    ports:
      - 8554:8554
      - 1935:1935
      - 8888:8888
      - 8889:8889
      - 8890:8890/udp
    volumes:
      - ./media-server/mediamtx.yml:/mediamtx.yml:Z
  ffmpeg:
    build:
      context: ./ffmpeg
    command: ffmpeg -re -stream_loop -1 -ss 06:49:38 -i collingwood.mp4 -c copy -f rtsp rtsp://mediamtx:8554/collingwood
    volumes:
      - ${VIDEO_PATH}:/collingwood.mp4:Z
    depends_on:
      - mediamtx