# Generated by Django 4.2.6 on 2023-11-18 02:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=30)),
                ('selection', models.JSONField(default=dict, verbose_name='selection')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('creation_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(null=True)),
                ('out_time', models.DateTimeField(null=True)),
                ('last_seen', models.DateTimeField(null=True)),
                ('obj_id', models.CharField()),
                ('obj_type', models.CharField()),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.parkingspace')),
                ('runtime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cams.runtime')),
            ],
        ),
    ]
