# Generated by Django 4.2.6 on 2023-10-28 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=30)),
                ('cameraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('ParkingSpaceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.parkingspace')),
            ],
        ),
    ]
