# Generated by Django 4.2.6 on 2023-10-28 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='ParkingSpaceId',
            new_name='parkingSpaceId',
        ),
    ]
