# Generated by Django 4.2.6 on 2023-10-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0002_rename_parkingspaceid_point_parkingspaceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspace',
            old_name='cameraID',
            new_name='camera',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='parkingSpaceId',
            new_name='parking_space',
        ),
    ]
