# Generated by Django 4.2.6 on 2023-11-07 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0003_rename_cameraid_parkingspace_camera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('obj_id', models.CharField()),
                ('obj_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.objecttypes')),
                ('parking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.parkingspace')),
            ],
        ),
    ]
