# Generated by Django 4.2.6 on 2023-10-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygons', models.JSONField()),
                ('cameraID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cams.camera')),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingLot',
        ),
    ]
